name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thanks for creating an Issue, We will be eager to solve it.'
        pr-message: 'Thank you for the contrubuition, Welcome to Tkinter Designer team. 🎉'
